### ISSUE TITLE
Problem with packing

### ISSUE THREAD

**Issue by linakima** [Dir-A/YurisTools#3]
I unpacked and packed the [game](https://f95zone.to/threads/euphoria-final-clock-up.638/) archive with the texts. 
I didn't change anything in those files, just unpacked and packed. 
But the game does not accept the new archive. 
I have also tried using YSPac.exe from the yu-ris_0490 engine to pack new files in 4_ybn_done folder. But I get the same error.
And where can I get the CRC 32 key?
![1](https://github.com/Dir-A/YurisTools/assets/34077156/71c6e58c-a32a-4835-8a7d-8ad2952657c9)
![2](https://github.com/Dir-A/YurisTools/assets/34077156/4286c9c9-e829-4bfe-8e15-e47a788f1a39)
![3](https://github.com/Dir-A/YurisTools/assets/34077156/058753ca-0070-4c61-be0a-050fb01daff3)
[source ypf.zip](https://github.com/Dir-A/YurisTools/files/12129367/ypf.zip)

**Comment by imKota** [comment]
@linakima try this `GameExtractor.exe ypf -c -v 466 update`
Where **update** it's name for new file **update.ypf** 
[GameExtractor.zip](https://github.com/Dir-A/YurisTools/files/12130050/GameExtractor.zip)

**Comment by linakima** [comment]
@Dir-A I deleted the original bn.ypf file and replaced it with the files from the 1_ybn_unpacked folder. 
When I start the game, I get a message about the licence. The game does not start.

![1](https://github.com/Dir-A/YurisTools/assets/34077156/47f111fc-324e-4544-8d2e-5f75b7d3a449)

@imKota I tried two options.
1. I put the update file next to bn.ypf. I got an error in file #87. I didn't change anything in the modified files. Just unzipped - decrypted - encrypted - put in the update folder.

![2](https://github.com/Dir-A/YurisTools/assets/34077156/392361c6-c873-438a-a2b5-d26c9f777a77)

2. I deleted the bn.ypf file and renamed the update.ypf file to bn.ypf and put it in the game folder. I got another error.

![3](https://github.com/Dir-A/YurisTools/assets/34077156/22a41030-c242-45f2-ae74-becbb828b92a)

[update_ypf.zip](https://github.com/Dir-A/YurisTools/files/12130421/update_ypf.zip)

**Comment by linakima** [comment]
@imKota discord sima0488

**Comment by Dir-A** [comment]
[Euphoria_en.zip](https://github.com/Dir-A/YurisTools/files/12130824/Euphoria_en.zip)
Extract the zip to game directory

I've modified yuris' read file priority,
Now you just need to keep the directory structure that unpack frome pack and put files in the game directory.
The ysbin folder is unpacked from the bn.ypf,
It's decrypted and I've removed the decryption key from the game's program, 
which means that if any of ybn's text editor tools ask for xorkey it's 0x0.

**Comment by linakima** [comment]
@Dir-A I've tried different folder locations. In the root of the game, in the pac folder. Through the bin folder or directly through ysbin. I always get a licence error. I ran it through euphoria_en.exe.

![4](https://github.com/Dir-A/YurisTools/assets/34077156/c0b42f64-53c2-4777-b978-60799ff25e11)
![5](https://github.com/Dir-A/YurisTools/assets/34077156/c54ed8f5-8698-43be-b57a-4ac3cadc527c)

I can't unzip the update.ypf file.
The programme is looking for something on the D drive.
But I don't have such a drive on my computer.
This folder path is written into the programme.
![sd](https://github.com/Dir-A/YurisTools/assets/34077156/c530743b-1f3c-4192-9477-446f90ea5940)

**Comment by linakima** [comment]
My bad. Your open folder is working fine.

**Comment by linakima** [comment]
@Dir-A 
Can you tell me exactly what needs to be changed in the .exe file using the hex editor? So that I can repeat these actions for other games on this engine and not worry you any more.

**Comment by imKota** [comment]
@linakima This part will decide the load localtion priority.
Open Ollydbg and check the file load routing, change to 0123 sequence to force application load local file first.

![1](https://github.com/Dir-A/YurisTools/assets/24241471/02f39548-4cdc-4686-b3c0-2e0434a0ac9e)

**Comment by linakima** [comment]
Thanks!

**Comment by Dir-A** [comment]
It's a bit complicated.
I've recorded videos on this, but only in Chinese. 
https://www.youtube.com/watch?v=5Ijv_otByLw
43:16

In short, the new version of yuirs engine has three ways to read files
Read from memory, Read from packet,Read from game directory

There are two places where read priority is controlled.
1、the game exe
2、yscfg.ybn file

The yuris engine can controls how each file is read.
In the game exe there is an array, 0, 1, 2, 3
These 0, 1, 2 and 3 actually correspond to different read modes.

There are probably very many places like this array inside game exe
Of course we can change them one by one

But we just need to find the read priority of the file yscfg.ybn and change it to read from the game directory
Then we can modify the yscfg.ybn file, as there are three parameters inside this file that control the read mode of all files.

Check the video above
49:33  -> Find the read mode control array
55:28  -> Modify yscfg.ybn
